Merged PR 103900: Fix for a recursive exception while closing a briefcase
We log that the briefcase is closed. However, the metadata for that log calls BriefcaseEntry.getDebugInfo, which calls getBriefcaseSize.

The stat call in getBriefcaseSize throws (since the local file has already been deleted) and we log the exception (calling getDebugInfo again for metatdata and thus entering recursion).

---

RangeError: Maximum call stack size exceeded\n    at Function.makeMetaData (D:\\source\\project-extents-editor-backend\\dist\\main.js:105546:24)\n    at Function.formatMetaData (D:\\source\\project-extents-editor-backend\\dist\\main.js:105555:44)\n    at Function._logError (D:\\source\\project-extents-editor-backend\\dist\\main.js:105490:124)\n    at Function.logError (D:\\source\\project-extents-editor-backend\\dist\\main.js:105654:20)\n    at BriefcaseEntry.getBriefcaseSize (D:\\source\\project-extents-editor-backend\\dist\\main.js:33520:37)\n    at BriefcaseEntry.getBriefcaseProps (D:\\source\\project-extents-editor-backend\\dist\\main.js:33534:28)\n    at BriefcaseEntry.getDebugInfo (D:\\source\\project-extents-editor-backend\\dist\\main.js:33553:53)\n    at D:\\source\\project-extents-editor-backend\\dist\\main.js:33520:113\n    at Function.makeMetaData (D:\\source\\project-extents-editor-backend\\dist\\main.js:105547:58)\n    at Function.formatMetaData (D:\\source\\project-extents-editor-backend\\dist\\main.js:105555:44)\n    at Function._logError (D:\\source\\project-extents-editor-backend\\dist\\main.js:105490:124)\n    at Function.logError (D:\\source\\project-extents-editor-backend\\dist\\main.js:105654:20)\n    at BriefcaseEntry.getBriefcaseSize (D:\\source\\project-extents-editor-backend\\dist\\main.js:33520:37)\n    at BriefcaseEntry.getBriefcaseProps (D:\\source\\project-extents-editor-backend\\dist\\main.js:33534:28)\n    at BriefcaseEntry.getDebugInfo (D:\\source\\project-extents-editor-backend\\dist\\main.js:33553:53)\n    at D:\\source\\project-extents-editor-backend\\dist\\main.js:33520:113\n    at Function.makeMetaData (D:\\source\\project-extents-editor-backend\\dist\\main.js:105547:58)\n    at Function.formatMetaData (D:\\source\\project-extents-editor-backend\\dist\\main.js:105555:44)\n    at Function._logError (D:\\source\\project-extents-editor-backend\\dist\\main.js:105490:124)\n    at Function.logError (D:\\source\\project-extents-editor-backend\\dist\\main.js:105654:20)\n    at BriefcaseEntry.getBriefcaseSize (D:\\source\\project-extents-editor-backend\\dist\\main.js:33520:37)\n    at BriefcaseEntry.getBriefcaseProps (D:\\source\\project-extents-editor-backend\\dist\\main.js:33534:28)